FROM resin/rpi-raspbian:latest
RUN apt-get -y update
RUN apt-get -y install \
	gcc \
	build-essential \
	git \
	make \
	mosquitto

#packet forwarder for imst iC880A
WORKDIR /opt

##  driver / hardware abstraction layer source
RUN git clone https://github.com/Lora-net/lora_gateway.git

## the packet_forwarder source
RUN git clone https://github.com/Lora-net/packet_forwarder.git

## repo with systemd rule
RUN git clone https://github.com/dejwoo/systemctl-packetforwarder

## build driver/HAL
WORKDIR /opt/lora_gateway
RUN make all

## build packet_forwarder
WORKDIR /opt/packet_forwarder
RUN make all

## run script to create packet_forwarder user and place systemd rule
WORKDIR /opt/systemctl-packetforwarder
RUN chmod u+x ./install.sh
# 44454641554c5430 -> DEFAULT0
ENV PACKET_FORWARDER_GATEWAY_ID=44454641554c5430
ENV PACKET_FORWARDER_SERVER_ADDRESS= 0.0.0.0
ENV PACKET_FORWARDER_SERV_PORT_UP=1680
ENV PACKET_FORWARDER_SERV_PORT_DOWN=1680
ENV PACKET_FORWARDER_KEEPALIVE_INTERVAL=10
ENV PACKET_FORWARDER_STAT_INTERVAL=30
ENV PACKET_FORWARDER_PUSH_TIMEOUT_MS=100
ENV PACKET_FORWARDER_FORWARD_CRC_VALID=true
ENV PACKET_FORWARDER_FORWARD_CRC_ERROR=false
ENV PACKET_FORWARDER_FORWARD_CRC_DISABLED=false
RUN ./install.sh

EXPOSE $PACKET_FORWARDER_SERV_PORT_UP
EXPOSE $PACKET_FORWARDER_SERV_PORT_DOWN
